# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. See: vagrantup.com.

  # Build against CentOS 6.4, without any config management utilities.
  #config.vm.box = "chef/centos-7.0"
  #config.vm.box = "bento/centos-7.1"
  config.vm.box = "centos/7"
  #config.vm.box = "magmadigital/centos-7.0"
  #config.vm.box_url = ""

  # Enable host-only access to the machine using a specific IP.
  # config.vm.network :private_network, ip: "192.168.10.100"

  # Enable port forwarding 
  #config.vm.network :forwarded_port, host: 3000, guest: 3000
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.network :forwarded_port, host: 8443, guest: 443
  #config.vm.network :forwarded_port, host: 8080, guest: 8080

  # Shared folders.
  # You can only use NFS (second option below) once nfs-utils is installed.
  # config.vm.synced_folder "/path/to/local/folder", "/path/to/remote"
  # config.vm.synced_folder "/path/to/local/folder", "/path/to/remote",
  #   :nfs => !RUBY_PLATFORM.downcase.include?("w32"),
  #   id: "share"

  # Provider-specific configuration for VirtualBox.
  config.vm.provider :virtualbox do |v|
    #v.customize ["modifyvm", :id, "--name", "indaba"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--cpus", 4]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    #ansible.groups = {
    # "indaba" => ["default"]
    #}

    ansible.playbook = "../ansible/playbook.yml"
    # Enable verbose output.
    ansible.verbose = "vv"
    # Run commands as root.
    ansible.sudo = true
    ansible.host_key_checking = false
    # ansible.raw_arguments = ['-v']
  end

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  # config.vm.define :indaba do |indaba|
  #   indaba.vm.hostname = "indaba"
  # end

end